### ISSUE TITLE
Markdown for jekyll syntax is very good

### ISSUE THREAD

**Issue by y377** [taufik-nurrohman/highlight.ln.js#4]
## Current environment:

1. [highlight.js](https://cdn.jsdelivr.net/npm/@highlightjs/cdn-assets@11.3.1/highlight.min.js)
2. [jekyll](https://jekyllrb.com/)
3. [bootstrap](https://getbootstrap.com/)
4. [highlight.ln.js](https://github.com/taufik-nurrohman/highlight.ln.js)
**The four of them used together without conflict**

![image](https://user-images.githubusercontent.com/58632405/145711056-ae8f9e36-4949-47ce-9d5a-e79b07b7202f.png)
![image](https://user-images.githubusercontent.com/58632405/145711071-81290420-2383-4826-bda3-ab9b5ea10348.png)
Thanks for developing such a useful plug-in, how to adapt the "Markdown" syntax, thank you very much!
Expected effect: delete unnecessary line breaks at the end of the code

-------------------------

## Effect after repair：

![image](https://user-images.githubusercontent.com/58632405/145726821-2c982a81-6670-4624-b469-5c15e9353f50.png)

**Comment by taufik-nurrohman** [comment]
I think this has nothing to do with either _Highlight.js_ or this plugin. It depends on the Markdown parser you are using. If you go to https://parsedown.org/extra/ and test a code block markup, you will see that _Markdown Extra_ will add an extra line-break at the end of the code but not with _Parsedown Extra_.

![Test](https://user-images.githubusercontent.com/1669261/145712921-91539e36-391e-4dfc-93f8-38727365647f.png)

**Comment by y377** [comment]
Thank you for your reply, because I am not good at JavaScript, so I won’t modify it, please refer to this [highlightjs-line-numbers.min.js](https://cdnjs.cloudflare.com/ajax/libs/highlightjs-line-numbers.js/2.8.0/highlightjs-line-numbers.min.js), it has no line breaks，thank you!

--------------

**The face-to-face difference is the addition of the <td> tag**

![image](https://user-images.githubusercontent.com/58632405/145725343-790dd52f-b55f-4fd7-a844-d43f4ba550f1.png)

--------------

**If you can add the <td> tag, it can be effectively solved, but I don’t know JavaScript**

![image](https://user-images.githubusercontent.com/58632405/145725415-07ba8c1e-43ee-4227-9b53-db512a907dc6.png)
--------
I was still thinking that the processing here is too rough, it has been fixed now, thank you

> `lines.innerHTML = numbers.join('\n');`

**Comment by taufik-nurrohman** [comment]
For a quick fix, you can replace [this line](https://github.com/taufik-nurrohman/highlight.ln.js/blob/v1.0.0/highlight.ln.js#L20):

~~~ js
for (let i = 0, j = block.textContent.split(/\n/).length; i < j; ++i) {
~~~

With this:

~~~ js
for (let i = 0, j = block.textContent.trimEnd().split(/\n/).length; i < j; ++i) {
~~~
