### ISSUE TITLE
Please customize the line number color. Do not use the same color as the text

### ISSUE THREAD

**Issue by y377** [taufik-nurrohman/highlight.ln.js#5]
`lines.className = 'hljs'; // Inherit `background` and `padding` from the style sheet`
![image](https://user-images.githubusercontent.com/58632405/146025199-b9a4d8c4-df54-4d9e-95ba-c8299a13ec41.png)

For example, the line number is customized to white

after repair :
![image](https://user-images.githubusercontent.com/58632405/146038126-52714efa-050f-45ce-a329-2d420f4d7cb8.png)

**Comment by taufik-nurrohman** [comment]
You can modify the line number CSS this way:

~~~ css
pre .hljs[style]:first-child {
  background: black !important;
  border-right-color: cyan !important; /* here to change the border color */
  color: white !important;
}
~~~
